<?php


const ACTIVITE_TABLE_NAME = 'Activite';
const CLIENT_TABLE_NAME = 'Client';
const COLLABORATEUR_TABLE_NAME = 'Collaborateur';
const CONTACT_TABLE_NAME = 'Contact';
const CONTRAT_TABLE_NAME = 'Contrat';
const DOCUMENT_TABLE_NAME = 'Document';
const ETAPE_TABLE_NAME = 'Etape';
const FONCTION_TABLE_NAME = 'Fonction';
const INTERVENTION_TABLE_NAME = 'Intervention';
const PROJET_TABLE_NAME = 'Projet';

const DB_TABLE_NAMES = [
  ACTIVITE_TABLE_NAME,
  CLIENT_TABLE_NAME,
  COLLABORATEUR_TABLE_NAME,
  CONTACT_TABLE_NAME,
  CONTRAT_TABLE_NAME,
  DOCUMENT_TABLE_NAME,
  ETAPE_TABLE_NAME,
  FONCTION_TABLE_NAME,
  INTERVENTION_TABLE_NAME,
  PROJET_TABLE_NAME
];

const ACTIVITE_ID_ACTIVITE_DBFIELD = 'id_activite';
const ACTIVITE_LIBELLE_ACTIVITE_DBFIELD = 'libelle_activite';

const ACTIVITE_FIELDS_NAME = [
  ACTIVITE_ID_ACTIVITE_DBFIELD,
  ACTIVITE_LIBELLE_ACTIVITE_DBFIELD
];

const CLIENT_CODE_CLIENT_DBFIELD = 'code_client';
const CLIENT_TYPE_CLIENT_DBFIELD = 'type_client';
const CLIENT_DOMAINE_ACTIVITE_DBFIELD = 'domaine_activite';
const CLIENT_NATURE_ACTIVITE_DBFIELD = 'nature_activite';
const CLIENT_RAISON_SOCIALE_DBFIELD = 'raison_sociale';
const CLIENT_CHIFFRE_AFFAIRES_DBFIELD = 'chiffre_affaires';
const CLIENT_EFFECTIFS_DBFIELD = 'effectifs';
const CLIENT_COMMENTAIRES_COMMERCIAUX_CLIENT_DBFIELD = 'commentaires_commerciaux_client';

const CLIENT_FIELDS_NAME = [
  CLIENT_CODE_CLIENT_DBFIELD,
  CLIENT_TYPE_CLIENT_DBFIELD,
  CLIENT_DOMAINE_ACTIVITE_DBFIELD,
  CLIENT_NATURE_ACTIVITE_DBFIELD,
  CLIENT_RAISON_SOCIALE_DBFIELD,
  CLIENT_CHIFFRE_AFFAIRES_DBFIELD,
  CLIENT_EFFECTIFS_DBFIELD,
  CLIENT_COMMENTAIRES_COMMERCIAUX_CLIENT_DBFIELD
];

const COLLABORATEUR_MATRICULE_DBFIELD = 'matricule';
const COLLABORATEUR_NOM_COLLABORATEUR_DBFIELD = 'nom_collaborateur';
const COLLABORATEUR_PRENOM_COLLABORATEUR_DBFIELD = 'prenom_collaborateur';
const COLLABORATEUR_SEXE_COLLABORATEUR_DBFIELD = 'sexe_collaborateur';
const COLLABORATEUR_ETAT_CIVIL_COLLABORATEUR_DBFIELD = 'etat_civil_collaborateur';
const COLLABORATEUR_ID_FONCTION_DBFIELD = 'id_fonction';

const COLLABORATEUR_FIELDS_NAME = [
  COLLABORATEUR_MATRICULE_DBFIELD,
  COLLABORATEUR_NOM_COLLABORATEUR_DBFIELD,
  COLLABORATEUR_PRENOM_COLLABORATEUR_DBFIELD,
  COLLABORATEUR_SEXE_COLLABORATEUR_DBFIELD,
  COLLABORATEUR_ETAT_CIVIL_COLLABORATEUR_DBFIELD,
  COLLABORATEUR_ID_FONCTION_DBFIELD
];

const CONTACT_ID_CONTACT_DBFIELD = 'id_contact';
const CONTACT_NOM_CONTACT_DBFIELD = 'nom_contact';
const CONTACT_PRENOM_CONTACT_DBFIELD = 'prenom_contact';
const CONTACT_EMAIL_CONTACT_DBFIELD = 'email_contact';
const CONTACT_TEL_CONTACT_DBFIELD = 'tel_contact';
const CONTACT_CODE_PROJET_DBFIELD = 'code_projet';
const CONTACT_CODE_CLIENT_DBFIELD = 'code_client';

const CONTACT_FIELDS_NAME = [
  CONTACT_ID_CONTACT_DBFIELD,
  CONTACT_NOM_CONTACT_DBFIELD,
  CONTACT_PRENOM_CONTACT_DBFIELD,
  CONTACT_EMAIL_CONTACT_DBFIELD,
  CONTACT_TEL_CONTACT_DBFIELD,
  CONTACT_CODE_PROJET_DBFIELD,
  CONTACT_CODE_CLIENT_DBFIELD
];

const CONTRAT_ID_CONTRAT_DBFIELD = 'id_contrat';
const CONTRAT_DATE_DEBUT_CONTRAT_DBFIELD = 'date_debut_contrat';
const CONTRAT_DATE_FIN_CONTRAT_DBFIELD = 'date_fin_contrat';
const CONTRAT_LIBELLE_CONTRAT_DBFIELD = 'libelle_contrat';
const CONTRAT_SALAIRE_DBFIELD = 'salaire';
const CONTRAT_TYPE_DBFIELD = 'type';
const CONTRAT_MATRICULE_DBFIELD = 'matricule';

const CONTRAT_FIELDS_NAME = [
  CONTRAT_ID_CONTRAT_DBFIELD,
  CONTRAT_DATE_DEBUT_CONTRAT_DBFIELD,
  CONTRAT_DATE_FIN_CONTRAT_DBFIELD,
  CONTRAT_LIBELLE_CONTRAT_DBFIELD,
  CONTRAT_SALAIRE_DBFIELD,
  CONTRAT_TYPE_DBFIELD,
  CONTRAT_MATRICULE_DBFIELD
];

const DOCUMENT_ID_DOCUMENT_DBFIELD = 'id_document';
const DOCUMENT_TITRE_DOCUMENT_DBFIELD = 'titre_document';
const DOCUMENT_RESUME_DOCUMENT_DBFIELD = 'resume_document';
const DOCUMENT_DATE_DIFFUSION_DOCUMENT_DBFIELD = 'date_diffusion_document';
const DOCUMENT_CODE_PROJET_DBFIELD = 'code_projet';
const DOCUMENT_MATRICULE_DBFIELD = 'matricule';

const DOCUMENT_FIELDS_NAME = [
  DOCUMENT_ID_DOCUMENT_DBFIELD,
  DOCUMENT_TITRE_DOCUMENT_DBFIELD,
  DOCUMENT_RESUME_DOCUMENT_DBFIELD,
  DOCUMENT_DATE_DIFFUSION_DOCUMENT_DBFIELD,
  DOCUMENT_CODE_PROJET_DBFIELD,
  DOCUMENT_MATRICULE_DBFIELD
];

const ETAPE_NUM_LOT_DBFIELD = 'num_lot';
const ETAPE_CHARGE_ESTIMEE_DBFIELD = 'charge_estimee';
const ETAPE_CHARGE_REELLE_PROD_DBFIELD = 'charge_reelle_prod';
const ETAPE_CHARGE_REELLE_VALIDATION_DBFIELD = 'charge_reelle_validation';
const ETAPE_ID_ACTIVITE_DBFIELD = 'id_activite';
const ETAPE_CODE_PROJET_DBFIELD = 'code_projet';

const ETAPE_FIELDS_NAME = [
  ETAPE_NUM_LOT_DBFIELD,
  ETAPE_CHARGE_ESTIMEE_DBFIELD,
  ETAPE_CHARGE_REELLE_PROD_DBFIELD,
  ETAPE_CHARGE_REELLE_VALIDATION_DBFIELD,
  ETAPE_ID_ACTIVITE_DBFIELD,
  ETAPE_CODE_PROJET_DBFIELD
];

const FONCTION_ID_FONCTION_DBFIELD = 'id_fonction';
const FONCTION_LIBELLE_FONCTION_DBFIELD = 'libelle_fonction';

const FONCTION_FIELDS_NAME = [
  FONCTION_ID_FONCTION_DBFIELD,
  FONCTION_LIBELLE_FONCTION_DBFIELD
];

const INTERVENTION_ID_INTERVENTION_DBFIELD = 'id_intervention';
const INTERVENTION_DATE_DEBUT_INTERVENTION_DBFIELD = 'date_debut_intervention';
const INTERVENTION_DATE_FIN_INTERVENTION_DBFIELD = 'date_fin_intervention';
const INTERVENTION_LIBELLE_INTERVENTION_DBFIELD = 'libelle_intervention';
const INTERVENTION_MATRICULE_DBFIELD = 'matricule';
const INTERVENTION_NUM_LOT_DBFIELD = 'num_lot';
const INTERVENTION_ID_FONCTION_DBFIELD = 'id_fonction';

const INTERVENTION_FIELDS_NAME = [
  INTERVENTION_ID_INTERVENTION_DBFIELD,
  INTERVENTION_DATE_DEBUT_INTERVENTION_DBFIELD,
  INTERVENTION_DATE_FIN_INTERVENTION_DBFIELD,
  INTERVENTION_LIBELLE_INTERVENTION_DBFIELD,
  INTERVENTION_MATRICULE_DBFIELD,
  INTERVENTION_NUM_LOT_DBFIELD,
  INTERVENTION_ID_FONCTION_DBFIELD
];

const PROJET_CODE_PROJET_DBFIELD = 'code_projet';
const PROJET_LIBELLE_LONG_PROJET_DBFIELD = 'libelle_long_projet';
const PROJET_LIBELLE_COURT_PROJET_DBFIELD = 'libelle_court_projet';
const PROJET_TYPE_PROJET_DBFIELD = 'type_projet';
const PROJET_CYCLE_VIE_PROJET_DBFIELD = 'cycle_vie_projet';
const PROJET_INFOS_TECHNIQUES_PROJET_DBFIELD = 'infos_techniques_projet';
const PROJET_CHARGE_ESTIMEE_PROJET_DBFIELD = 'charge_estimee_projet';
const PROJET_REMARQUES_ESTIMATION_PROJET_DBFIELD = 'remarques_estimation_projet';
const PROJET_DATE_DEBUT_PREVUE_DBFIELD = 'date_debut_prevue';
const PROJET_DATE_FIN_PREVUE_DBFIELD = 'date_fin_prevue';
const PROJET_DATE_DEBUT_REELLE_DBFIELD = 'date_debut_reelle';
const PROJET_DATE_FIN_REELLE_DBFIELD = 'date_fin_reelle';
const PROJET_EQUIPE_MAX_PROJET_DBFIELD = 'equipe_max_projet';
const PROJET_COMMENTAIRES_COMMERCIAUX_PROJET_DBFIELD = 'commentaires_commerciaux_projet';
const PROJET_SECTEUR_ACTIVITE_DBFIELD = 'secteur_activite';
const PROJET_MATRICULE_DBFIELD = 'matricule';
const PROJET_CODE_CLIENT_DBFIELD = 'code_client';

const PROJET_FIELDS_NAME = [
  PROJET_CODE_PROJET_DBFIELD,
  PROJET_LIBELLE_LONG_PROJET_DBFIELD,
  PROJET_LIBELLE_COURT_PROJET_DBFIELD,
  PROJET_TYPE_PROJET_DBFIELD,
  PROJET_CYCLE_VIE_PROJET_DBFIELD,
  PROJET_INFOS_TECHNIQUES_PROJET_DBFIELD,
  PROJET_CHARGE_ESTIMEE_PROJET_DBFIELD,
  PROJET_REMARQUES_ESTIMATION_PROJET_DBFIELD,
  PROJET_DATE_DEBUT_PREVUE_DBFIELD,
  PROJET_DATE_FIN_PREVUE_DBFIELD,
  PROJET_DATE_DEBUT_REELLE_DBFIELD,
  PROJET_DATE_FIN_REELLE_DBFIELD,
  PROJET_EQUIPE_MAX_PROJET_DBFIELD,
  PROJET_COMMENTAIRES_COMMERCIAUX_PROJET_DBFIELD,
  PROJET_SECTEUR_ACTIVITE_DBFIELD,
  PROJET_MATRICULE_DBFIELD,
  PROJET_CODE_CLIENT_DBFIELD
];